services:
  postgres_db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: tutor
    networks:
      - api-network

  api-rest-java:
    build: .
    container_name: api-rest-java
    ports:
      - "8080:8080"
    depends_on:
      - postgres_db
    networks:
      - api-network
    environment:
      SERVER_PORT: 8080   # ← aquí se fuerza Spring Boot a usar 8080
      SPRING_PROFILES_ACTIVE: docker  # opcional, si tienes un profile específico para Docker

networks:
  api-network:
    driver: bridge
