##################################################
# Configuración general de la aplicación
##################################################
spring.application.name=servicio-rest
spring.devtools.restart.enabled=true
server.port=0

##################################################
# Configuración de la base de datos (PostgreSQL)
##################################################
spring.datasource.url=jdbc:postgresql://localhost:5432/tutor
spring.datasource.username=admin
spring.datasource.password=admin123
spring.datasource.driver-class-name=org.postgresql.Driver

##################################################
# Configuración de JPA / Hibernate
##################################################
# ddl-auto puede ser: none, validate, update, create, create-drop
spring.jpa.hibernate.ddl-auto=update

# Mostrar las consultas SQL en la consola
spring.jpa.show-sql=true

# Dialecto de PostgreSQL para Hibernate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# URL del Swagger UI
springdoc.swagger-ui.path=/swagger-ui.html
# URL base de los endpoints OpenAPI
springdoc.api-docs.path=/v3/api-docs


# Configuración JWT
jwt.secret=EstaEsMiClaveSuperSecretaParaJWT123456
jwt.expiration=3600000



spring.security.user.name=admin
spring.security.user.password=MiPassword123


spring.security.enabled=false